### ISSUE TITLE
npm test fails with origin issue

### ISSUE THREAD

**Issue by bryanpizzillo** [NCIOCPL/clinical-trials-search-app#261]
### Issue description
 `npm test` does not work on the develop branch.  See error below.
 
> **ESTIMATE** TBD

```
 PASS  src/utilities/__tests__/queryStringToFormObject.basic.positive.js
Error: Cross origin http://localhost forbidden
    at dispatchError (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at Object.validCORSHeaders (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:72:5)
    at receiveResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:843:21)
    at Request.<anonymous> (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:678:38)
    at Request.emit (events.js:314:20)
    at Request.onRequestResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/request/request.js:1066:10)
    at OverriddenClientRequest.emit (events.js:314:20)
    at respond (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:300:11)
    at respondUsingInterceptor (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:342:7)
    at /Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:282:7 undefined
Error: Cross origin http://localhost forbidden
    at dispatchError (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at Object.validCORSHeaders (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:72:5)
    at receiveResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:843:21)
    at Request.<anonymous> (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:678:38)
    at Request.emit (events.js:314:20)
    at Request.onRequestResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/request/request.js:1066:10)
    at OverriddenClientRequest.emit (events.js:314:20)
    at respond (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:300:11)
    at respondUsingInterceptor (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:342:7)
    at /Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:282:7 undefined
Error: Cross origin http://localhost forbidden
    at dispatchError (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at Object.validCORSHeaders (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:72:5)
    at receiveResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:843:21)
    at Request.<anonymous> (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:678:38)
    at Request.emit (events.js:314:20)
    at Request.onRequestResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/request/request.js:1066:10)
    at OverriddenClientRequest.emit (events.js:314:20)
    at respond (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:300:11)
    at respondUsingInterceptor (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:342:7)
    at /Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:282:7 undefined
Error: Cross origin http://localhost forbidden
    at dispatchError (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:60:19)
    at Object.validCORSHeaders (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:72:5)
    at receiveResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:843:21)
    at Request.<anonymous> (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/jest-environment-jsdom-fourteen/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:678:38)
    at Request.emit (events.js:314:20)
    at Request.onRequestResponse (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/request/request.js:1066:10)
    at OverriddenClientRequest.emit (events.js:314:20)
    at respond (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:300:11)
    at respondUsingInterceptor (/Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:342:7)
    at /Volumes/Development/nciocpl/clinical-trials-search-app/node_modules/nock/lib/playback_interceptor.js:282:7 undefined
```

**Comment by bryanpizzillo** [comment]
It looks like this is related to https://github.com/axios/axios issue 2654.
